CREATE DATABASE ms_citas;

\c ms_citas

-- Tabla 'servicio'
CREATE TABLE servicio (
    codigo VARCHAR(255) NOT NULL,
    descripcion VARCHAR(255),
    PRIMARY KEY (codigo)
);

-- Tabla 'actividad'
CREATE TABLE actividad (
    codigo VARCHAR(255) NOT NULL,
    descripcion VARCHAR(255),
    servicio VARCHAR(255) NOT NULL,
    PRIMARY KEY (codigo),
    FOREIGN KEY (servicio) REFERENCES servicio(codigo)
);

-- Tabla 'consultorio'
CREATE TABLE consultorio (
    codigo BIGINT GENERATED BY DEFAULT AS IDENTITY,
    descripcion VARCHAR(255),
    PRIMARY KEY (codigo)
);

-- Tabla 'diagnostico'
CREATE TABLE diagnostico (
    codigo VARCHAR(255) NOT NULL,
    descripcion VARCHAR(255),
    PRIMARY KEY (codigo)
);

-- Tabla 'cita'
CREATE TABLE cita (
    episodio BIGINT GENERATED BY DEFAULT AS IDENTITY,
    estado VARCHAR(255),
    fecha_cita TIMESTAMP(6),
    fecha_pedido TIMESTAMP(6),
    historia BIGINT,
    actividad VARCHAR(255) NOT NULL,
    consultorio BIGINT NOT NULL,
    diagnostico VARCHAR(255),
    PRIMARY KEY (episodio),
    FOREIGN KEY (actividad) REFERENCES actividad(codigo),
    FOREIGN KEY (consultorio) REFERENCES consultorio(codigo),
    FOREIGN KEY (diagnostico) REFERENCES diagnostico(codigo)
);

